account:
  path: /
  controller: App\Controller\Account\AccountController::indexAction

account-edit:
  path: /edit
  controller: App\Controller\Account\AccountController::editAction

account-organizations:
  path: /organizations
  controller: App\Controller\Account\AccountController::orgaAction

account-orga-leave:
  path: /organizations/leave/{id}
  controller: App\Controller\Account\AccountController::orgaLeaveAction
  requirements:
    id: \d+

account-orga-add-user:
  path: /organizations/add-user
  controller: App\Controller\Account\AccountController::orgaAddUserAction

account-orga-remove:
  path: /organizations/remove/{orga_id}/{user_id}
  controller: App\Controller\Account\AccountController::orgaRemoveAction
  requirements:
    orga_id: \d+
    user_id: \d+

account-delete-apikey:
  path: /delete-api-key/{id}
  controller: App\Controller\Account\AccountController::deleteApiKeyAction
  requirements:
    id: .+
