admin-dashboard:
  path: /
  controller: App\Controller\Management\Admin\AdminDashboardController::indexAction

admin-users:
  path: /users
  controller: App\Controller\Management\Admin\UsersController::indexAction

admin-screens:
  path: /screens
  controller: App\Controller\Management\Admin\ScreenController::indexAction

admin-organizations:
  path: /organizations
  controller: App\Controller\Management\Admin\OrganizationsController::indexAction

admin-invitation-codes:
  path: /invitation-codes
  controller: App\Controller\Management\Admin\InvitationCodesController::indexAction

admin-invitation-create-one:
  path: /invitation-codes/create/one
  controller: App\Controller\Management\Admin\InvitationCodesController::createOneAction

admin-invitation-create-generate-one:
  path: /invitation-codes/create/generateOne
  controller: App\Controller\Management\Admin\InvitationCodesController::createGenerateOneAction

admin-invitation-create-generate-multiple:
  path: /invitation-codes/create/generateMultiple
  controller: App\Controller\Management\Admin\InvitationCodesController::createGenerateMultipleAction

admin-invitation-delete:
  path: /invitation-codes/delete/{codeData}
  controller: App\Controller\Management\Admin\InvitationCodesController::deleteAction
  requirements:
    codeData: .+
