endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 400
        margin: 10
        encoding: 'UTF-8'
        errorCorrectionLevel: 'high'
        validateResult: false
