jms_serializer:
  metadata:
    auto_detection: false
    infer_types_from_doctrine_metadata: false
    directories:
      app:
        namespace_prefix: "App\\Entity"
        path: "%kernel.project_dir%/config/jms_serializer"
    warmup:
      paths:
        included:
          - "%kernel.project_dir%/src/Entity"
          - "%kernel.project_dir%/src/Presentation"
          - "%kernel.project_dir%/src/Presentation/Slideshow"
          - "%kernel.project_dir%/src/Presentation/Slideshow/Slides"
