# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

    email:
        enabled: true
        digits: 6
        sender_email: '%env(MAILER_FROM)%'
        sender_name: Shinage Two-Factor Authentification
        template: security/2fa_form.html.twig
        mailer: 'App\Security\TwoFactorCodeMailer'

    backup_codes:
        enabled: true

    google:
        enabled: true
        server_name: Shinage
        issuer: Shinage
        template: security/2fa_form.html.twig
