twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/semantic-ui-form-theme.html.twig'
    globals:
        version_checker: '@App\Service\VersionChecker'
