filter:
    paths:
        - "src/"

build:
    environment:
        php:
            version: 7.4.13
            compile_options: '--enable-gd --with-openssl --enable-mbstring --enable-intl'
    nodes:
        analysis:
            environment:
                node:
                    version: v10.14.2
    tests:
        override: ['php -v']

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: true
            before_parentheses:
                closure_definition: true
