filter:
    paths:
        - "app/"
        - "src/"
        - "web/"
    excluded_paths:
        - "web/js/jstree/"
        - "web/js/jquery-ui/"
        - "web/js/lib/"
        - "web/js/elfinder/"
        - "web/js/fullcalendar/"
        - "web/js/jquery.datetimepicker.full.min.js"
        - "web/semantic-ui/"
        - "web/app*.php"
        - "src/AppBundle/spec/"
        - "src/AppBundle/tests/"

build:
    tests:
        override: ['php -v']

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: true
