filter:
    paths:
        - "src/"

build:
    environment:
        php:
            version: 8.0.13
            compile_options: '--enable-gd --with-openssl --enable-mbstring --enable-intl'
    nodes:
        analysis:
            environment:
                node:
                    version: v14.18.2
    tests:
        override:
            - php-scrutinizer-run
