# 2fa
_2fa:
  resource: ./scheb_two_factor.yaml

_qr:
  prefix: /qr
  resource: '@EndroidQrCodeBundle/Resources/config/routes.yaml'

_account:
  prefix: /account
  resource: ./manage/account.yml

_admin:
  prefix: /adm
  resource: ./manage/admin.yml

_screen:
  prefix: /screen
  resource: ./manage/screen.yml

_presentation_editors:
  prefix: /presentations/
  resource: ./manage/presentation.yml

management-dashboard:
  path: /dashboard
  controller: App\Controller\Management\DashboardController::dashboardAction

management-dashboard-preview:
  path: /dashboard/preview/{screen_guid}
  controller: App\Controller\Management\DashboardController::previewAction
  requirements:
    screen_guid: '.+'  # TODO

management-presentations:
  path: /presentations/list/{viewMode}
  controller: App\Controller\Management\PresentationsController::managePresentationsAction
  defaults:
    viewMode: 'large'

management-presentations-create:
  path: /presentations/create
  controller: App\Controller\Management\PresentationsController::createPresentationAction

presentation-delete:
  path: /presentations/delete/{presentationId}
  controller: App\Controller\Management\PresentationsController::deletePresentationAction
  requirements:
    presentationId: '\d+'

presentation-save-title:
  path: /presentations/save-title/
  controller: App\Controller\Management\PresentationsController::savePresentationTitle
  methods: [ post ]

presentation-save-notes:
  path: /presentations/save-notes/
  controller: App\Controller\Management\PresentationsController::savePresentationNotes
  methods: [ post ]

presentation-change-owner:
  path: /presentations/change-owner
  controller: App\Controller\Management\PresentationsController::savePresentationOwner

management-preview:
  path: /preview
  controller: App\Controller\Management\PreviewController::previewAction


# @TODO Move scheduler routes into own namespace

management-scheduler:
  path: /scheduler
  controller: App\Controller\Management\SchedulerController::schedulerAction

management-get-schedule:
  path: /get-schedule
  controller: App\Controller\Management\SchedulerController::getScheduleAction

management-edit-scheduled:
  path: /edit-scheduled
  controller: App\Controller\Management\SchedulerController::editScheduledAction

management-change-scheduled:
  path: /change-scheduled
  controller: App\Controller\Management\SchedulerController::changeScheduledAction

management-delete-scheduled:
  path: /delete-scheduled
  controller: App\Controller\Management\SchedulerController::deleteScheduledAction


management-files:
  path: /files
  controller: App\Controller\Management\FileManager::filesAction


management-files-download:
  path: /files-download/{file}
  controller: App\Controller\Management\FileManager::downloadAction
  requirements:
    file: .+

management-files-el-thumbnail:
  path: /files-el-thumbnail/{base}/{file}
  controller: App\Controller\Management\FileManager::elThumbnailAction
  requirements:
    base: .*
    file: .*

management-files-connector:
  path: /files-connector
  controller: App\Controller\Management\FileManager::connectorAction

management-get-possible-owners:
  path: /ajax/get-possible-owners
  controller: App\Controller\Management\OwnersController::getPossibleOwnersAction
