# TODO screen-guid-requirement genauer angeben

screen-remote-heartbeat:
  path: /heartbeat/{screenId}
  controller: App\Controller\ScreenRemote\HeartbeatController::heartbeatAction
  requirements:
    screenId: .+

current-for:
  path: /current-for/{guid}
  controller: App\Controller\ScreenRemote\CurrentForController::indexAction
  requirements:
    guid: .+

screen-remote-screenshot:
  path: /upload-screenshot
  controller: App\Controller\ScreenRemote\HeartbeatController::uploadScreenshotAction
