# TODO screen-guid-requirement genauer angeben

screen-remote-heartbeat:
  path: /heartbeat/{screenId}
  controller: App\Controller\ScreenRemote\HeartbeatController::heartbeatAction
  requirements:
    screenId: .+

current-for:
  path: /current-for/{guid}
  controller: App\Controller\ScreenRemote\CurrentForController::indexAction
  requirements:
    guid: .+

screen-remote-presentation:
  path: /presentation/{id}
  controller: App\Controller\ScreenRemote\HeartbeatController::presentationAction
  requirements:
    id: \d+

screen-remote-client-file:
  path: /client-file/{file}
  controller: App\Controller\ScreenRemote\HeartbeatController::clientFileAction
  requirements:
    file: .+

screen-remote-screenshot:
  path: /upload-screenshot
  controller: App\Controller\ScreenRemote\HeartbeatController::uploadScreenshotAction
