services:
  AppBundle\Controller\:
    resource: ../../../Controller
    autowire: true
    autoconfigure: false
    public: true
    tags: ['controller.service_arguments']

  AppBundle\Controller\Api\v1\FilesController:
    arguments:
      $filePoolPermissionChecker: '@app.filepool.permission_checker'
      $tokenStorage: '@security.token_storage'
      $filePoolBasePath: '%path_pool%'

