services:
  AppBundle\Presentation\AnyPresentationRenderer:
    arguments:
      - '@app.presentation.presentation_type_registry'

  app.presentation.presentation_type_registry:
    class: AppBundle\Presentation\PresentationTypeRegistry


  app.presentation.type.website:
    class: AppBundle\Presentation\GenericPresentationType
    arguments:
      - 'website'
      - '@app.presentation.type.website.renderer'
    tags:
      - app.presentation_type

  app.presentation.type.website.renderer:
    class: AppBundle\Presentation\Website\Renderer
    arguments:
      - '@app.presentation.type.website.settings_reader'

  app.presentation.type.website.settings_reader:
    class: AppBundle\Presentation\GenericSettingsReader
    arguments:
      - '@jms_serializer.serializer'
      - 'AppBundle\Presentation\Website\Settings'


  app.presentation.type.slideshow:
    class: AppBundle\Presentation\GenericPresentationType
    arguments:
      - 'slideshow'
      - '@app.presentation.type.slideshow.renderer'
    tags:
      - app.presentation_type

  app.presentation.type.slideshow.renderer:
    class: AppBundle\Presentation\Slideshow\Renderer
    arguments:
      - '@app.presentation.type.slideshow.settings_reader'

  app.presentation.type.slideshow.settings_reader:
    class: AppBundle\Presentation\GenericSettingsReader
    arguments:
      - '@jms_serializer.serializer'
      - 'AppBundle\Presentation\Slideshow\Settings'


  app.presentation.type.mirror:
    class: AppBundle\Presentation\GenericPresentationType
    arguments:
      - 'mirror'
      - '@app.presentation.type.mirror.renderer'
    tags:
      - app.presentation_type

  app.presentation.type.mirror.renderer:
    class: AppBundle\Presentation\Mirror\Renderer
    arguments:
      - '@app.presentation.type.mirror.settings_reader'

  app.presentation.type.mirror.settings_reader:
    class: AppBundle\Presentation\GenericSettingsReader
    arguments:
      - '@jms_serializer.serializer'
      - 'AppBundle\Presentation\Mirror\Settings'


#    app.presentation.type.multipane:
#        class: AppBundle\Service\PresentationBuilders\MultiPanePresentation
#        tags:
#            - app.presentation_type
#        arguments:
#            $serializer: '@jms_serializer'
