services:
  app.security.voters.screen:
    class: AppBundle\Security\Voters\ScreenVoter
    arguments:
      $screenAssociation: '@app.screenassociation'
    tags:
    - security.voter

  app.security.path_checker:
    class: AppBundle\Security\PathChecker
