imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type:   console
            channels: ["!event", "!doctrine"]

#swiftmailer:
#    delivery_address: me@example.com

shinage_player:
  uuid: "00000000-0000-0000-0000-000000000000"
  local:
    enabled: false
    path: "/mnt/usb"
  remote:
    enabled: true
    host: "nginx"
    protocol: "http"
    base_path: "/"
    controller:
      heartbeat: "/screen-remote/heartbeat/%s"
      presentation: "/screen-remote/presentation/%d"
      asset: "/screen-remote/client-file/%s"
      screenshot: "/screen-remote/upload-screenshot"

