app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

shinage_management:
    prefix: "manage"
    resource: "@AppBundle/Resources/config/routing.yml"

shinage_player:
    prefix: "virtual_player"
    resource: "@ShinagePlayerBundle/Resources/config/routing.yml"

shinage_online_player:
    prefix: "online_player"
    resource: "@ShinageOnlinePlayerBundle/Resources/config/routing.yml"
