app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

shinage_player:
    prefix: "virtual_player"
    resource: "@ShinagePlayerBundle/Resources/config/routing.yml"
