# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.screenassociation:
        class: AppBundle\Service\ScreenAssociation
        arguments:
            em: "@doctrine.orm.entity_manager"

    app.filepool:
        class: AppBundle\Service\FilePool
        arguments:
            basepath: %path_pool%
