#fos_user:
#  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

shinage_management:
  prefix: "manage"
  resource: "routes/routing_manage.yml"

shinage_presentations:
  prefix: "presentations"
  resource: "routes/routing_presentations.yml"

shinage_api_v1:
  prefix: "/api/v1"
  resource: "routes/api_v1.yml"

_screen_remote_api:
  prefix: "/screen-remote"
  resource: "routes/screen_remote.yml"


# Security
shinage_register:
  prefix: "/register"
  resource: "routes/register.yml"

_fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_show:
  path: /profile
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: management-dashboard
    permanent: false
    keepQueryParams: false

_fos_user_resetting:
  prefix: /resetting
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"


homepage:
  path: "/"
  controller: App\Controller\DefaultController::indexAction

pool-get:
  path: /pool/{userRoot}/{path}
  controller: App\Controller\PoolController::getAction
  requirements:
    userRoot: "[^/]*"
    path: ".*"

pool-get-root:
  path: /pool/

qr-for-screen-registration:
  path: /qr/register-screen/{connectCode}
  controller: App\Controller\QrController::registerScreenUrlAction
  requirements:
    connectCode: .+
