fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

shinage_management:
  prefix: "manage"
  resource: "routes/routing_manage.yml"

shinage_presentations:
  prefix: "presentations"
  resource: "routes/routing_presentations.yml"

shinage_api_v1:
  prefix: "/api/v1"
  resource: "routes/api_v1.yml"

_screen_remote_api:
  prefix: "/screen-remote"
  resource: "routes/screen_remote.yml"

shinage_register:
  prefix: "/register"
  resource: "routes/register.yml"

homepage:
  path: "/"
  controller: App\Controller\DefaultController::indexAction

shinage_player:
  prefix: "virtual_player"
  resource: "@ShinagePlayerBundle/Resources/config/routing.yml"

pool-get:
  path: /pool/{userRoot}/{path}
  controller: App\Controller\PoolController::getAction
  requirements:
    userRoot: "[^/]*"
    path: ".*"

pool-get-root:
  path: /pool/
