services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Tests\Behat\:
        resource: '../tests/Behat/*'

    Tests\Behat\Client\ApiV1ClientContext:
        arguments:
            - "http://127.0.0.1:8000"
            # @TODO Make it somehow autoconfigured

    Tests\Behat\Hook\PurgeContext:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%swiftmailer.spool.default.file.path%"
            # @TODO Make it somehow autoconfigured


    #shinage\server\behat\:
    #    resource: '../features/bootstrap/*'
    #    exclude: '../features/bootstrap/bootstrap.php'

imports:
    - "../features/bootstrap/config/services.yml"

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
