services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Tests\Behat\:
        resource: '../tests/Behat/*'

    Tests\Behat\Client\ApiV1ClientContext:
        arguments:
            - "http://127.0.0.1:8000"
            # @TODO Make it somehow autoconfigured

    Tests\Behat\Hook\PurgeContext:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%swiftmailer.spool.default.file.path%"
            # @TODO Make it somehow autoconfigured

    Tests\Behat\Setup\FilePoolContext:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Tests\Behat\Service\SharedStorage'
            - '@Tests\Behat\Hook\PurgeContext'
            - '%path_pool%'

    Tests\Behat\Gui\LoginContext:
        arguments:
            - "@fos_user.user_manager"
            - "@session"
            - "main"

    Tests\Behat\MailContext:
        arguments:
            - "%swiftmailer.spool.default.file.path%"

    Symfony\Component\BrowserKit\Client:
        alias: test.client

    behat.mink:
        class: Behat\MinkExtension\Context\MinkContext

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
