services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Tests\Behat\:
        resource: '../tests/Behat/*'

    Tests\Behat\Client\ApiV1ClientContext:
        arguments:
            $baseUrl: "http://127.0.0.1:8000"
            # @TODO Make it somehow autoconfigured

    Tests\Behat\Hook\PurgeContext:
        arguments:
            $mailSpoolPath: "%swiftmailer.spool.default.file.path%"

    Tests\Behat\Setup\FilePoolContext:
        arguments:
            $basePath: '%path_pool%'

    Tests\Behat\Gui\LoginContext:
        arguments:
            $session: "@session"
            $firewallName: "main"

    Tests\Behat\MailContext:
        arguments:
            $spoolDir: "%swiftmailer.spool.default.file.path%"

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
