_account:
  prefix: /account
  resource: ./routing/account.yml

_admin:
  prefix: /adm
  resource: ./routing/admin.yml

_screen:
  prefix: /screen
  resource: ./routing/screen.yml


management-dashboard:
  path: /dashboard
  controller: AppBundle\Controller\Management\DashboardController::dashboardAction

management-dashboard-preview:
  path: /dashboard/preview/{screen_guid}
  controller: AppBundle\Controller\Management\DashboardController::previewAction
  requirements:
    screen_guid: '.+'  # TODO

management-presentations:
  path: /presentations
  controller: AppBundle\Controller\Management\PresentationsController::managePresentationsAction

management-presentations-create:
  path: /presentations/create
  controller: AppBundle\Controller\Management\PresentationsController::createPresentationAction

presentation-delete:
  path: /presentations/delete/{presentationId}
  controller: AppBundle\Controller\Management\PresentationsController::createPresentationAction
  requirements:
    presentationId: '\d+'


management-preview:
  path: /preview
  controller: AppBundle\Controller\Management\PreviewController::previewAction


management-scheduler:
  path: /scheduler
  controller: AppBundle\Controller\Management\SchedulerController::schedulerAction

management-get-schedule:
  path: /get-schedule
  controller: AppBundle\Controller\Management\SchedulerController::getScheduleAction

management-add-scheduled:
  path: /add-scheduled
  controller: AppBundle\Controller\Management\SchedulerController::addScheduledAction

management-change-scheduled:
  path: /change-scheduled
  controller: AppBundle\Controller\Management\SchedulerController::changeScheduledAction

management-delete-scheduled:
  path: /delete-scheduled
  controller: AppBundle\Controller\Management\SchedulerController::deleteScheduledAction
