services:
    app.screenassociation:
        class: AppBundle\Service\ScreenAssociation
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $tokenStorage: "@security.token_storage"

    app.scheduler:
        class: AppBundle\Service\SchedulerService
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $tokenStorage: "@security.token_storage"

    app.orgamanager:
        class: AppBundle\Service\OrganizationManager
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $tokenStorage: "@security.token_storage"

    app.filepool:
        class: AppBundle\Service\FilePool
        arguments:
            $basepath: "%path_pool%"

    app.apiroleregistry:
        class: AppBundle\Service\ApiRoleRegistry

    app.remote.playable_builder:
        class: AppBundle\Service\Remote\PlayableBuilder
        arguments:
            $router: "@router"

    app.todolist:
        class: AppBundle\Service\TodoList
        arguments:
            $basepath: "%kernel.root_dir%"
            $cache: "@cache.app"

    app.registration.listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            $router: "@router.default"
        tags:
            - { name: kernel.event_subscriber }

    app.form.type.owner:
        class: AppBundle\Form\Type\OwnerType
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $tokenStorage: "@security.token_storage"
        tags:
            - { name: form.type }

    app.form.type.apikeyform:
        class: AppBundle\Form\ApiKeyForm
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $tokenStorage: "@security.token_storage"
        tags:
            - { name: form.type }

    app.presentation_builder_chain:
        class: AppBundle\Service\PresentationBuilders\PresentationBuilderChain

    app.presentations.mirror:
        class: AppBundle\Service\PresentationBuilders\MirrorPresentation
        tags:
            - app.presentation_builder
