AppBundle\Entity\Slide:
  type: entity
  table: slides
  id:
    id:
      type: integer
      length: null
      unique: false
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    slide_type:
      type: string
      length: 100
      unique: false
      nullable: false
    duration:
      type: integer
      length: null
      unique: false
      nullable: false
    notes:
      type: text
      length: null
      unique: false
      nullable: false
    file_path:
      type: text
      length: null
      unique: false
      nullable: false
    sort_order:
      type: integer
      length: null
      unique: false
      nullable: false
  manyToOne:
    presentation:
      targetEntity: AppBundle\Entity\Presentation
      fetch: LAZY
      mappedBy: null
      inversedBy: slides
      joinColumns:
        presentation_id:
          referencedColumnName: id
          nullable: false
      orphanRemoval: false
  lifecycleCallbacks: {  }
