AppBundle\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      length: null
      unique: false
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    userType:
      type: enumusertype
      length: null
      unique: false
      nullable: false
      column: user_type
    name:
      type: string
      length: 200
      unique: false
      nullable: false
  manyToMany:
    organizations:
      targetEntity: AppBundle\Entity\User
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinTable:
        name: users_orgas
        schema: null
        joinColumns:
          -
            name: user_id
            unique: false
            nullable: true
            onDelete: null
            columnDefinition: null
            referencedColumnName: id
        inverseJoinColumns:
          -
            name: organization_id
            unique: false
            nullable: true
            onDelete: null
            columnDefinition: null
            referencedColumnName: id
      orderBy: null
  lifecycleCallbacks: {  }
