App\Entity\RegistrationCode:
  type: entity
  table: registration_codes
  id:
    code:
      type: string
      length: 250
      unique: true
      nullable: false
      id: true
      generator:
        strategy: NONE
  fields:
    createdDate:
      type: datetime
      unique: false
      nullable: false
      column: created_date
    validUntil:
      type: datetime
      unique: false
      nullable: false
      column: valid_until
  manyToOne:
    createdBy:
      targetEntity: App\Entity\User
      fetch: EAGER
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: id
          nullable: true
      orphanRemoval: false
    assignOrganization:
      targetEntity: App\Entity\User
      fetch: EAGER
      mappedBy: null
      inversedBy: null
      joinColumns:
        assign_organization:
          referencedColumnName: id
          nullable: true
      orphanRemoval: false
