App\Entity\ScreenAssociation:
  type: entity
  table: screen_associations
  id:
    id:
      type: integer
      length: null
      unique: false
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    roles:
      type: simple_array
      length: 255
      unique: false
      nullable: false
  manyToOne:
    screen:
      targetEntity: App\Entity\Screen
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        screen_id:
          referencedColumnName: guid
          nullable: false
      orphanRemoval: false
    user:
      targetEntity: App\Entity\User
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
