App\Entity\ScreenCommand:
  type: entity
  table: screen_commands
  id:
    id:
      type: integer
      length: null
      unique: false
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  indexes:
    screen_fetched_index:
      columns: [ screen_id , fetched ]
  fields:
    created:
      type: datetime
      unique: false
      nullable: false
    fetched:
      type: datetime
      unique: false
      nullable: true
    command:
      type: string
      length: 255
      unique: false
      nullable: false
    arguments:
      type: json
      unique: false
      nullable: false
  manyToOne:
    screen:
      targetEntity: App\Entity\Screen
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        screen_id:
          referencedColumnName: guid
          nullable: false
      orphanRemoval: false
    user:
      targetEntity: App\Entity\User
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
      nullable: true
  lifecycleCallbacks: {  }
