App\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      length: null
      unique: false
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    userType:
      type: string
      length: 32
      unique: false
      nullable: false
      column: user_type
    name:
      type: string
      length: 200
      unique: false
      nullable: false
    emailAuthEnabled:
      type: boolean
      unique: false
      nullable: false
      default: false
    emailAuthCode:
      type: string
      length: 6
      unique: false
      nullable: true
    totpSecret:
      type: string
      length: 200
      unique: false
      nullable: true
    backupCodes:
      type: json_array
      unique: false
      nullable: true
    orgaAssignAutomaticallyByMailHost:
      type: boolean
      unique: false
      nullable: false
      default: false
      column: auto_assign_by_mailhost

  manyToMany:
    users:
      targetEntity: App\Entity\User
      mappedBy: organizations
    organizations:
      targetEntity: App\Entity\User
      fetch: LAZY
      mappedBy: null
      inversedBy: users
      joinTable:
        name: users_orgas
        schema: null
        joinColumns:
          -
            name: user_id
            unique: false
            nullable: true
            onDelete: null
            columnDefinition: null
            referencedColumnName: id
        inverseJoinColumns:
          -
            name: organization_id
            unique: false
            nullable: true
            onDelete: null
            columnDefinition: null
            referencedColumnName: id
      orderBy: null
  lifecycleCallbacks: {  }
